steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.fastboot
      repo: ${CI_REPO}
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
